server:
  port: 8089

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3309/boot_crm?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT
    username: root
    password: w123456
    #        阿里巴巴数据库链接池配置
    type: com.alibaba.druid.pool.DruidDataSource
  # 彩色日志
  output:
    ansi:
      enabled: ALWAYS

  redis:
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-active: 8   # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1    # 连接池最大阻塞等待时间（使用负值表示没有限制
        max-idle: 500   # 连接池中的最大空闲连接
        min-idle:  0    # 连接池中的最小空闲连接
      shutdown-timeout: 100 #在关闭客户端连接之前等待任务处理完成的最长时间,都会被执行器关闭，默认100m
    timeout: 10000      # 超时时间
  mvc:
    servlet:
      load-on-startup: 100
  servlet:
    multipart:
      enabled: true   # 项目允许上传文件
      location: D:/tmp/uploadfiles      # 上传文件的临时目录 （一般情况下不用特意修改）
      max-file-size: 104857600  #上传文件最大为 10M （默认值 1M 根据自身业务自行控制即可）
      max-request-size: 104857600 #上传请求最大为 10M（默认值10M 根据自身业务自行控制即可）
      file-size-threshold: 0      #文件大小阈值，当大于这个阈值时将写入到磁盘，否则存在内存中，（默认值0 一般情况下不用特意修改）
      resolve-lazily: false #判断是否要延迟解析文件（相当于懒加载，一般情况下不用特意修改）

mybatis-plus:
  mapper-locations: classpath:/mapper/*/*.xml
  type-aliases-package: com.example.easypoi.pojo
  global-config:
    db-config:
      id-type: auto
  configuration:
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl